### PR TITLE
this commit is to the task1 of the 2

### PR DESCRIPTION
**Pull request by muffinboy19**
Issue: 1

fg

### CODE REVIEW

**Review by muffinboy19 — COMMENTED** [review]
issue:1

**Comment by aditya-rai01** [comment]
@muffinboy19 solve merge conflict

**Comment by muffinboy19** [comment]
sir men form bhara hai ..

**Comment by aditya-rai01** [comment]
@muffinboy19 yeah, you have filled the form

**Comment by muffinboy19** [comment]
sir i have filled the leaderboard form

**Pull request merged**
