### PR TITLE
 this is c1 of t1

### PR DESCRIPTION
**Pull request by insanecoder02**
Issue: 1

i changed something 

this change shows my faviouote movie 
-

### CODE REVIEW

**Comment by aditya-rai01** [comment]
@insanecoder02 solve merge conflict

**Comment by insanecoder02** [comment]
sir pls merge it

**Comment by insanecoder02** [comment]
sir why is my branch not merging ..

**Comment by aditya-rai01** [comment]
@insanecoder02 still there is merge conflict

**Pull request merged**
